INS_MAX_LEN = 4                         # in bytes the max len c16x instruction can be
MEM_PAGE_SIZE = 0x4000                  # page size 
ROM_MAP_START_ADDRESS = 0x800000        # 0x800000 is the address from where the eeprom is mapped in memory
ROM_DATA_MAP_START_ADDRESS = 0x810000   # 0x810000 is the address where eeprom data is mapped to (eg. maps data)
RAM_MAP_START_ADDRESS = 0x380000        # ram is mapped to memory from 0x380000

class Instruction:
    # init method or constructor
    def __init__(self, opcode, name, inslen):
        self._name = name
        self._opcode = opcode
        self._inslen = inslen

    def get_opcode(self):
        return self._opcode
    def get_len(self):
        return self._inslen
    def get_name(self):
        return self._name

class DisasmInstruction(Instruction):
    # pass some bytes to the object
    # we will try and map it to an instruction
    def __init__(self, bytes):
        for i in instruction_set:
            if i.get_opcode() == bytes[0]:
                Instruction.__init__(
                    self, 
                    i.get_opcode(),
                    i.get_name(),
                    i.get_len()
                )
                self._bytes = bytes[:self._inslen]
                return
        raise Exception("Unrecognized instruction")

    def read_bytes(self):
        return self._bytes

    def read_mnemonic(self):
        # temp
        return self.get_name()

 
instruction_set = [
    Instruction(opcode=0x00, name="add",    inslen=2),
    Instruction(opcode=0x01, name="addb",   inslen=2),
    Instruction(opcode=0x02, name="add",    inslen=4),
    Instruction(opcode=0x03, name="addb",   inslen=4),
    Instruction(opcode=0x04, name="add",    inslen=4),
    Instruction(opcode=0x05, name="addb",   inslen=4),
    Instruction(opcode=0x06, name="add",    inslen=4),
    Instruction(opcode=0x07, name="addb",   inslen=4),
    Instruction(opcode=0x08, name="add",    inslen=2),
    Instruction(opcode=0x09, name="addb",   inslen=2),
    Instruction(opcode=0x0a, name="bfldl",  inslen=4),
    Instruction(opcode=0x0b, name="mul",    inslen=2),
    Instruction(opcode=0x0c, name="rol",    inslen=2),
    Instruction(opcode=0x0d, name="jmpr",   inslen=2),
    Instruction(opcode=0x0e, name="bclr",   inslen=2),
    Instruction(opcode=0x0f, name="bset",   inslen=2),

    Instruction(opcode=0x10, name="addc",   inslen=2),
    Instruction(opcode=0x11, name="addcb",  inslen=2),
    Instruction(opcode=0x12, name="addc",   inslen=4),
    Instruction(opcode=0x13, name="addcb",  inslen=4),
    Instruction(opcode=0x14, name="addc",   inslen=4),
    Instruction(opcode=0x15, name="addcb",  inslen=4),
    Instruction(opcode=0x16, name="addc",   inslen=4),
    Instruction(opcode=0x17, name="addcb",  inslen=4),
    Instruction(opcode=0x18, name="addc",   inslen=2),
    Instruction(opcode=0x19, name="addcb",  inslen=2),
    Instruction(opcode=0x1a, name="bfldl",  inslen=4),
    Instruction(opcode=0x1b, name="mulu",   inslen=2),
    Instruction(opcode=0x1c, name="rol",    inslen=2),
    Instruction(opcode=0x1d, name="jmpr",   inslen=2),
    Instruction(opcode=0x1e, name="bclr",   inslen=2),
    Instruction(opcode=0x1f, name="bset",   inslen=2),

    Instruction(opcode=0x20, name="sub",    inslen=2),
    Instruction(opcode=0x21, name="subb",   inslen=2),
    Instruction(opcode=0x22, name="sub",    inslen=4),
    Instruction(opcode=0x23, name="subb",   inslen=4),
    Instruction(opcode=0x24, name="sub",    inslen=4),
    Instruction(opcode=0x25, name="subb",   inslen=4),
    Instruction(opcode=0x26, name="sub",    inslen=4),
    Instruction(opcode=0x27, name="subb",   inslen=4),
    Instruction(opcode=0x28, name="sub",    inslen=2),
    Instruction(opcode=0x29, name="subb",   inslen=2),
    Instruction(opcode=0x2a, name="bcmp",   inslen=4),
    Instruction(opcode=0x2b, name="prior",  inslen=2),
    Instruction(opcode=0x2c, name="ror",    inslen=2),
    Instruction(opcode=0x2d, name="jmpr",   inslen=2),
    Instruction(opcode=0x2e, name="bclr",   inslen=2),
    Instruction(opcode=0x2f, name="bset",   inslen=2), 

    Instruction(opcode=0x30, name="subc",   inslen=2),
    Instruction(opcode=0x31, name="subcb",  inslen=2),
    Instruction(opcode=0x32, name="subc",   inslen=4),
    Instruction(opcode=0x33, name="subcb",  inslen=4),
    Instruction(opcode=0x34, name="subc",   inslen=4),
    Instruction(opcode=0x35, name="subcb",  inslen=4),
    Instruction(opcode=0x36, name="subc",   inslen=4),
    Instruction(opcode=0x37, name="subcb",  inslen=4),
    Instruction(opcode=0x38, name="subc",   inslen=2),
    Instruction(opcode=0x39, name="subcb",  inslen=2),
    Instruction(opcode=0x3a, name="bmovn",  inslen=4),
    Instruction(opcode=0x3b, name="-",      inslen=0),
    Instruction(opcode=0x3c, name="ror",    inslen=2),
    Instruction(opcode=0x3d, name="jmpr",   inslen=2),
    Instruction(opcode=0x3e, name="bclr",   inslen=2),
    Instruction(opcode=0x3f, name="bset",   inslen=2),

    Instruction(opcode=0x40, name="cmp",    inslen=2),
    Instruction(opcode=0x41, name="cmpb",   inslen=2),
    Instruction(opcode=0x42, name="cmp",    inslen=4),
    Instruction(opcode=0x43, name="cmpb",   inslen=4),
    Instruction(opcode=0x44, name="-",      inslen=0),
    Instruction(opcode=0x45, name="-",      inslen=0),
    Instruction(opcode=0x46, name="cmp",    inslen=4),
    Instruction(opcode=0x47, name="cmpb",   inslen=4),
    Instruction(opcode=0x48, name="cmp",    inslen=2),
    Instruction(opcode=0x49, name="cmpb",   inslen=2),
    Instruction(opcode=0x4a, name="bmov",   inslen=4),
    Instruction(opcode=0x4b, name="div",    inslen=2),
    Instruction(opcode=0x4c, name="shl",    inslen=2),
    Instruction(opcode=0x4d, name="jmpr",   inslen=2),
    Instruction(opcode=0x4e, name="bclr",   inslen=2),
    Instruction(opcode=0x4f, name="bset",   inslen=2),  

    Instruction(opcode=0x50, name="xor",    inslen=2),
    Instruction(opcode=0x51, name="xorb",   inslen=2),
    Instruction(opcode=0x52, name="xor",    inslen=4),
    Instruction(opcode=0x53, name="xorb",   inslen=4),
    Instruction(opcode=0x54, name="xor",    inslen=4),
    Instruction(opcode=0x55, name="xorb",   inslen=4),
    Instruction(opcode=0x56, name="xor",    inslen=4),
    Instruction(opcode=0x57, name="xorb",   inslen=4),
    Instruction(opcode=0x58, name="xor",    inslen=2),
    Instruction(opcode=0x59, name="xorb",   inslen=2),
    Instruction(opcode=0x5a, name="bor",    inslen=4),
    Instruction(opcode=0x5b, name="divu",   inslen=2),
    Instruction(opcode=0x5c, name="shl",    inslen=2),
    Instruction(opcode=0x5d, name="jmpr",   inslen=2),
    Instruction(opcode=0x5e, name="bclr",   inslen=2),
    Instruction(opcode=0x5f, name="bset",   inslen=2),        

    Instruction(opcode=0x60, name="and",    inslen=2),
    Instruction(opcode=0x61, name="andb!",  inslen=2),
    Instruction(opcode=0x62, name="and",    inslen=4),
    Instruction(opcode=0x63, name="andb",   inslen=4),
    Instruction(opcode=0x64, name="and",    inslen=4),
    Instruction(opcode=0x65, name="andb",   inslen=4),
    Instruction(opcode=0x66, name="and",    inslen=4),
    Instruction(opcode=0x67, name="andb",   inslen=4),
    Instruction(opcode=0x68, name="and",    inslen=2),
    Instruction(opcode=0x69, name="andb",   inslen=2),
    Instruction(opcode=0x6a, name="band",   inslen=4),
    Instruction(opcode=0x6b, name="divl",   inslen=2),
    Instruction(opcode=0x6c, name="shr",    inslen=2),
    Instruction(opcode=0x6d, name="jmpr",   inslen=2),
    Instruction(opcode=0x6e, name="bclr",   inslen=2),
    Instruction(opcode=0x6f, name="bset",   inslen=2), 

    Instruction(opcode=0x70, name="or",     inslen=2),
    Instruction(opcode=0x71, name="orb",    inslen=2),
    Instruction(opcode=0x72, name="or",     inslen=4),
    Instruction(opcode=0x73, name="orb",    inslen=4),
    Instruction(opcode=0x74, name="or",     inslen=4),
    Instruction(opcode=0x75, name="orb",    inslen=4),
    Instruction(opcode=0x76, name="or",     inslen=4),
    Instruction(opcode=0x77, name="orb",    inslen=4),
    Instruction(opcode=0x78, name="or",     inslen=2),
    Instruction(opcode=0x79, name="orb",    inslen=2),
    Instruction(opcode=0x7a, name="bxor",   inslen=4),
    Instruction(opcode=0x7b, name="divlu",  inslen=2),
    Instruction(opcode=0x7c, name="shr",    inslen=2),
    Instruction(opcode=0x7d, name="jmpr",   inslen=2),
    Instruction(opcode=0x7e, name="bclr",   inslen=2),
    Instruction(opcode=0x7f, name="bset",   inslen=2), 

    Instruction(opcode=0x80, name="cmpi1",  inslen=2),
    Instruction(opcode=0x81, name="neg",    inslen=2),
    Instruction(opcode=0x82, name="cmpi1",  inslen=4),
    Instruction(opcode=0x83, name="-",      inslen=0),
    Instruction(opcode=0x84, name="mov",    inslen=4),
    Instruction(opcode=0x85, name="-",      inslen=0),
    Instruction(opcode=0x86, name="cmpi1",  inslen=4),
    Instruction(opcode=0x87, name="idle",   inslen=4),
    Instruction(opcode=0x88, name="mov",    inslen=2),
    Instruction(opcode=0x89, name="movb",   inslen=2),
    Instruction(opcode=0x8a, name="jb",     inslen=4),
    Instruction(opcode=0x8b, name="-",      inslen=0),
    Instruction(opcode=0x8c, name="-",      inslen=0),
    Instruction(opcode=0x8d, name="jmpr",   inslen=2),
    Instruction(opcode=0x8e, name="bclr",   inslen=2),
    Instruction(opcode=0x8f, name="bset",   inslen=2), 

    Instruction(opcode=0x90, name="cmp2",   inslen=2),
    Instruction(opcode=0x91, name="cpl",    inslen=2),
    Instruction(opcode=0x92, name="cmpi2",  inslen=4),
    Instruction(opcode=0x93, name="-",      inslen=0),
    Instruction(opcode=0x94, name="mov",    inslen=4),
    Instruction(opcode=0x95, name="-",      inslen=0),
    Instruction(opcode=0x96, name="cmpi2",  inslen=4),
    Instruction(opcode=0x97, name="pwrdn",  inslen=4),
    Instruction(opcode=0x98, name="mov",    inslen=2),
    Instruction(opcode=0x99, name="movb",   inslen=2),
    Instruction(opcode=0x9a, name="jnb",    inslen=4),
    Instruction(opcode=0x9b, name="trap",   inslen=2),
    Instruction(opcode=0x9c, name="jmpi",   inslen=2),
    Instruction(opcode=0x9d, name="jmpr",   inslen=2),
    Instruction(opcode=0x9e, name="bclr",   inslen=2),
    Instruction(opcode=0x9f, name="bset",   inslen=2), 

    Instruction(opcode=0xa0, name="cmpd1",  inslen=2),
    Instruction(opcode=0xa1, name="negb",   inslen=2),
    Instruction(opcode=0xa2, name="cmpb1",  inslen=4),
    Instruction(opcode=0xa3, name="-",      inslen=0),
    Instruction(opcode=0xa4, name="movb",   inslen=4),
    Instruction(opcode=0xa5, name="diswdt", inslen=4),
    Instruction(opcode=0xa6, name="cmpd1",  inslen=4),
    Instruction(opcode=0xa7, name="-",      inslen=0),
    Instruction(opcode=0xa8, name="mov",    inslen=2),
    Instruction(opcode=0xa9, name="movb",   inslen=2),
    Instruction(opcode=0xaa, name="jbc",    inslen=4),
    Instruction(opcode=0xab, name="calli",  inslen=2),
    Instruction(opcode=0xac, name="ashr",   inslen=2),
    Instruction(opcode=0xad, name="jmpr",   inslen=2),
    Instruction(opcode=0xae, name="bclr",   inslen=2),
    Instruction(opcode=0xaf, name="bset",   inslen=2), 

    Instruction(opcode=0xb0, name="cmpd2",  inslen=2),
    Instruction(opcode=0xb1, name="cpl",    inslen=2),
    Instruction(opcode=0xb2, name="cmpd2",  inslen=4),
    Instruction(opcode=0xb3, name="-",      inslen=0),
    Instruction(opcode=0xb4, name="movb",   inslen=4),
    Instruction(opcode=0xb5, name="einit",  inslen=4),
    Instruction(opcode=0xb6, name="cmpd2",  inslen=4),
    Instruction(opcode=0xb7, name="srst",   inslen=4),
    Instruction(opcode=0xb8, name="mov",    inslen=2),
    Instruction(opcode=0xb9, name="movb",   inslen=2),
    Instruction(opcode=0xba, name="jnbs",   inslen=4),
    Instruction(opcode=0xbb, name="callr",  inslen=2),
    Instruction(opcode=0xbc, name="ashr",   inslen=2),
    Instruction(opcode=0xbd, name="jmpr",   inslen=2),
    Instruction(opcode=0xbe, name="bclr",   inslen=2),
    Instruction(opcode=0xbf, name="bset",   inslen=2), 

    Instruction(opcode=0xc0, name="movbz",  inslen=2),
    Instruction(opcode=0xc1, name="-",      inslen=0),
    Instruction(opcode=0xc2, name="movbz",  inslen=4),
    Instruction(opcode=0xc3, name="-",      inslen=0),
    Instruction(opcode=0xc4, name="mov",    inslen=4),
    Instruction(opcode=0xc5, name="movbz",  inslen=4),
    Instruction(opcode=0xc6, name="scxt",   inslen=4),
    Instruction(opcode=0xc7, name="-",      inslen=0),
    Instruction(opcode=0xc8, name="mov",    inslen=2),
    Instruction(opcode=0xc9, name="movb",   inslen=2),
    Instruction(opcode=0xca, name="calla",  inslen=4),
    Instruction(opcode=0xcb, name="ret",    inslen=2),
    Instruction(opcode=0xcc, name="nop",    inslen=2),
    Instruction(opcode=0xcd, name="jmpr",   inslen=2),
    Instruction(opcode=0xce, name="bclr",   inslen=2),
    Instruction(opcode=0xcf, name="bset",   inslen=2),   

    Instruction(opcode=0xd0, name="movbs",  inslen=2),
    Instruction(opcode=0xd1, name="atomic", inslen=2),
    Instruction(opcode=0xd2, name="movbs",  inslen=4),
    Instruction(opcode=0xd3, name="-",      inslen=0),
    Instruction(opcode=0xd4, name="mov",    inslen=4),
    Instruction(opcode=0xd5, name="movbs",  inslen=4),
    Instruction(opcode=0xd6, name="scxt",   inslen=4),
    Instruction(opcode=0xd7, name="extx",   inslen=4),
    Instruction(opcode=0xd8, name="mov",    inslen=2),
    Instruction(opcode=0xd9, name="movb",   inslen=2),
    Instruction(opcode=0xda, name="calls",  inslen=4),
    Instruction(opcode=0xdb, name="rets",   inslen=2),
    Instruction(opcode=0xdc, name="extx",   inslen=2),
    Instruction(opcode=0xdd, name="jmpr",   inslen=2),
    Instruction(opcode=0xde, name="bclr",   inslen=2),
    Instruction(opcode=0xdf, name="bset",   inslen=2), 

    Instruction(opcode=0xe0, name="mov",    inslen=2),
    Instruction(opcode=0xe1, name="movb",   inslen=2),
    Instruction(opcode=0xe2, name="pcall",  inslen=4),
    Instruction(opcode=0xe3, name="-",      inslen=0),
    Instruction(opcode=0xe4, name="movb",   inslen=4),
    Instruction(opcode=0xe5, name="-",      inslen=0),
    Instruction(opcode=0xe6, name="mov",    inslen=4),
    Instruction(opcode=0xe7, name="movb",   inslen=4),
    Instruction(opcode=0xe8, name="mov",    inslen=2),
    Instruction(opcode=0xe9, name="movb",   inslen=2),
    Instruction(opcode=0xea, name="jmpa",   inslen=4),
    Instruction(opcode=0xeb, name="retp",   inslen=2),
    Instruction(opcode=0xec, name="push",   inslen=2),
    Instruction(opcode=0xed, name="jmpr",   inslen=2),
    Instruction(opcode=0xee, name="bclr",   inslen=2),
    Instruction(opcode=0xef, name="bset",   inslen=2),   

    Instruction(opcode=0xf0, name="mov",    inslen=2),
    Instruction(opcode=0xf1, name="movb",   inslen=2),
    Instruction(opcode=0xf2, name="mov",    inslen=4),
    Instruction(opcode=0xf3, name="movb",   inslen=4),
    Instruction(opcode=0xf4, name="movb",   inslen=4),
    Instruction(opcode=0xf5, name="-",      inslen=0),
    Instruction(opcode=0xf6, name="mov",    inslen=4),
    Instruction(opcode=0xf7, name="movb",   inslen=4),
    Instruction(opcode=0xf8, name="-",      inslen=0),
    Instruction(opcode=0xf9, name="-",      inslen=0),
    Instruction(opcode=0xfa, name="jmps",   inslen=4),
    Instruction(opcode=0xfb, name="reti",   inslen=2),
    Instruction(opcode=0xfc, name="pop",    inslen=2),
    Instruction(opcode=0xfd, name="jmpr",   inslen=2),
    Instruction(opcode=0xfe, name="bclr",   inslen=2),
    Instruction(opcode=0xff, name="bset",   inslen=2)        
]
